### PR TITLE
Update Visual Styles

### PR DESCRIPTION
**Pull request by brianhall**
This migrates the existing index template over to Tailwind using the existing styles as a guide (breaks the visuals for subpages temporarily while those get ported over).

Also changes the trending data format slightly from `trending-up` and `trending-down` to just including the direction so that a more general `trending` style could be applied.

### CODE REVIEW

**Comment by brianhall** [comment]
@SlayterDev Here's the first pass on the index page, just getting it integrated with tailwind before moving on to make it prettier. This change will temporarily break the styles of the subpages, but I'm moving on to those right now. Let me know if you'd rather me put those changes in this PR instead.

**Comment by SlayterDev** [comment]
Love it! Yeah lets go ahead and add those here just so we don't break master.

**Comment by SlayterDev** [comment]
One comment though. It looks like we're losing the number on the Top 10 domains/entities. It would be nice to keep that since they're ranked.

**Comment by brianhall** [comment]
> One comment though. It looks like we're losing the number on the Top 10 domains/entities. It would be nice to keep that since they're ranked.

Totally, good call. I hadn't noticed that the css reset had nuked the numbers. Will bring those back.

**Comment by brianhall** [comment]
@SlayterDev I managed to finish up the remaining subpages and catch up with the latest changes in master. The PR is beastly, but if you pull and run it you should see the visual changes.

These changes should:
- standardize the visual layout across subpages
- establish a css framework we can extend in the future as the information changes
- implement a minor visual refresh

I'd like to do some more with the visuals, and will probably tackle that in the morning in a separate PR. Let me know if you have any questions / changes.

**Comment by SlayterDev** [comment]
Thank you @brianhall! This looks great. Really appreciate the help.

**Pull request merged**
