### PR TITLE
Fix Navigational Links

### PR DESCRIPTION
**Pull request by brianhall**
The navigational links in the header are currently broken because we're serving the wiki site from a subpath. This adds a config option so this can be altered.

Side note: we probably need to take a pass at some improvements for the sake of development, but that can certainly be done apart from hack days. :smile:

### CODE REVIEW

**Comment by brianhall** [comment]
@SlayterDev One more for you (hopefully the last one for now), just fixing the navigational links for production.

**Comment by SlayterDev** [comment]
We were using relative links to get around this before. Like `./` would be home and `./domains/example.com.html` etc. Would that not work here?

**Comment by brianhall** [comment]
@SlayterDev The main issue is that the relative links in the header won't work well for subpages, i.e. if you're on the page `domains/example.com.html` then click the home link that points to`./` then you're redirected to `domains/`, which  isn't a valid page.

**Comment by SlayterDev** [comment]
Yeah on subpages we were handling it using `../` to go back home haha. I’m mainly concerned it’ll break navigation links while developing locally.

**Comment by brianhall** [comment]
@SlayterDev Totally, I think it'd be worth taking a pass on filing some issues to fix the dev experience next week (including these links and perhaps keeping the site generation separate from the templates / dev setup).

**Pull request merged**
